# Site settings
title: Joanne Dekker Design
email: joannedekker@gmail.com
description: "Design portfolio of Joanne Dekker"
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://joannedekker.nl" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
